### ISSUE TITLE
Delete endpoints

### ISSUE THREAD

**Issue by Nefarious46** [teragrep/cfe_18#27]
**Description**

CFE-18 requires delete endpoints for data management. Build those using the same methods as done before on other endpoints.

=Procedure=
- [x] FileCaptureMeta
- [x] Sink
- [x] Flow
- [x] Capture
- [x] CaptureGroup
- [x] G_x_G
- [x] Host
- [x] HostMeta
- [x] Hub
- [x] HostGroup
- [x] Storage

=Endpoint=
- [x] FileCaptureMeta
- [x] Sink
- [x] Flow
- [x] Capture
- [x] CaptureGroup
- [x] G_x_G
- [x] Hub
- [x] Host
- [x] HostMeta
- [x] HostGroup
- [x] Storage

=E2ETest=
- [x] FileCaptureMeta
- [x] Sink
- [x] Flow
- [x] Capture
- [x] CaptureGroup
- [x] G_x_G
- [x] Host
- [x] HostMeta
- [x] Hub
- [x] HostGroup
- [x] Storage

**Comment by kortemik** [comment]
direct relation is preferred

ke 10. tammik. 2024 klo 16.50 Nefarious46 ***@***.***>
kirjoitti:
