### ISSUE TITLE
Update endpoints

### ISSUE THREAD

**Issue by Nefarious46** [teragrep/cfe_18#28]
**Description**

CFE-18 requires update endpoints for data management. Build those using the same methods as done before on other endpoints.

**Comment by kortemik** [comment]
SQL updates were rejected on the design phase. Are these a requirement of
some sort? Delete & Insert ftw

ma 8. tammik. 2024 klo 19.12 Nefarious46 ***@***.***>
kirjoitti:

**Comment by kortemik** [comment]
Preferably so

ti 9. tammik. 2024 klo 9.42 Nefarious46 ***@***.***>
kirjoitti:
