### ISSUE TITLE
Sink endpoints are not returning ID.

### ISSUE THREAD

**Issue by Nefarious46** [teragrep/cfe_18#31]
**Describe the bug**

 When fetching sinks from cfe-18 ID is not returned

**Expected behavior**

ID should be returned when fetching sinks
 
**How to reproduce**

Fetch sinks from cfe-18 endpoints
 
**Screenshots**

 
**Software version**

 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by kortemik** [comment]
hub is a host as well :)
