### ISSUE TITLE
The weird linkage behavior is now diagnosed, CFE-18 returns an ID lower than the "max" for the last linkage that is added when running the program. (Example, largest ID would be 5, last linkage returns 4 as a valid ID)

### ISSUE THREAD

**Issue by Nefarious46** [teragrep/cfe_18#62]
The weird linkage behavior is now diagnosed, CFE-18 returns an ID lower than the "max" for the last linkage that is added when running the program. (Example, largest ID would be 5, last linkage returns 4 as a valid ID)

This is ok behavior according to @Nefarious46, so I'm going to verify insertions completely compared to the main branch version.

_Originally posted by @MoonBow-1 in https://github.com/teragrep/cfe_31/issues/47#issuecomment-2042348834_

> Just to verify R__Procedure_add_g_x_g.sql where newly inserted rows ID is returned could be swapped from last_insert_id() to selecting the actual ID of the new row. This would be more consistent when returning the row ID which was created.

**Comment by MoonBow-1** [comment]
Going to comment on this issue:

This behavior persists on the main branch of [CFE-31](https://github.com/teragrep/cfe_31), so https://github.com/teragrep/cfe_31/issues/47 does not change the behavior.

**Comment by MoonBow-1** [comment]
Closed as invalid issue
